#ifndef RELAYX_COLLECTIONS_ERROR
#define RELAYX_COLLECTIONS_ERROR

typedef enum {
  C_OK = 0,
  C_NULL_REFERENCE,               
  C_OUT_OF_MEMORY,
  C_OUT_OF_RANGE, 
  C_ALREADY_CONSTRUCTED,
  C_ALREADY_DELETED     
} CError;

#endif // RELAYX_COLLECTIONS_ERROR